---
title: "Assignment 2"
author: 
  - Simon Alain Roger Gerdolle
  - Leonardo Gonnelli
  - Cédric Ly
date: "2025-03-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Install packages
```{r, message=FALSE, warning=FALSE}
library(dplyr)
library(ggplot2)
library(stringr)
library(readr)
```

# Part 1
## 1. Load data
```{r}
data2 <- read_csv("exercise2_cantons.csv")
View(data2)
```

## 2. Data Cleaning
```{r}
colnames(data2) <- c("all_columns")

data2 <- data2 %>%
  mutate(split_data = str_split(all_columns, ";")) %>%
  mutate(Canton = sapply(split_data, `[`, 1),
         GDP = as.numeric(sapply(split_data, `[`, 2)),
         Population = as.numeric(sapply(split_data, `[`, 3)),
         Immigration = as.numeric(sapply(split_data, `[`, 4))) %>%
  select(-all_columns, -split_data)

data2 <- data2 %>%
  filter(!Canton %in% c("Sri Lanka", "Liechtenstein"))
```

## 3. Correlation matrix (vu en classe)
```{r}
print(cor(select(data2, -canton), select(data2, -canton)))
```

## 4. Scatter Plot
```{r}

```

# Part 2
## 1. 
```{r}

```

## 2. lm -function (vu en classe)
```{r}
model <- lm(gdp ~ population, data = data)
print(model$coefficients)
```

## 3.
```{r}

```

## 4.
```{r}

```

## 5.
```{r}

```

## 6.
```{r}

```

# Part 3
## 1. 
```{r}

```

## 2. 
```{r}

```

## 3.
```{r}

```