---
title: "Assignment 2"
author: 
  - Simon Alain Roger Gerdolle
  - Leonardo Gonnelli
  - Cédric Ly
date: "2025-03-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#import packages
```{r}
library(readr)
library(ggplot2)
library(dplyr)
```

#load the data sets
```{r}
cleaned <- read_delim("ps2_cantons_cleaned.csv", delim = ";")
View(cleaned)
surnames <- read_delim("ps2_cantons_surnames.csv", delim = ",")
View(surnames)
```

#1. Data Preparation
```{r}
# Rename
surnames [12, "canton"] <- "St. Gallen"

# Merge data sets
merged_data <- cleaned %>%
  left_join(surnames %>% select(canton, share_mueller), by = "canton") %>%
  select(-immigration)
View(merged_data)

```

```{r}
# data checks
skimr::skim(merged_data)
print(merged_data$canton)

```

#2. Estimation of a univariate model
$$
gdp = \beta_0 + \beta_1 \cdot share \_mueller + u
$$
```{r}
model <- lm(gdp ~ share_mueller, data = merged_data)
print(model$coefficients)
```
$$
gdp = 8059.703 + 804465.380 \cdot share \_mueller + u
$$
interpretation :

```{r}
#prediction of gpd with share_mueller = 0,1
B0 <-  8059.703
B1 <- 804465.380
X <- 0.1

y = B0 + B1 * X
```

#3. Comparison of two univariate models
```{r}
model <- lm(gdp ~ population, data = merged_data)
print(model$coefficients)
```




