---
title: "Assignment 3"
author: 
  - Simon Alain Roger Gerdolle 23-611-940
  - Leonardo Gonnelli 23-617-111
  - Cédric Ly 23-615-487
date: "2025-03-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

# Import packages
```{r}
library(readr)
library(ggplot2)
library(dplyr)
```

```{r}
df3 <- read_csv("distances_birthtown-1.csv")
View(df3)
skimr::skim(df3)
```

## 1. Cleaning Data
```{r}
# Check 'medicine' variable format
unique(df3['medicine'])

# Encode 'medicine' variable
df3 <- mutate(df3, medicine = ifelse(medicine == "Yes", 1, 0))


# Set missing values for income variables
df3 <- mutate(df3, income = ifelse(income == -9999999, NaN, income)) %>%
  mutate(income_parent1 = ifelse(income_parent1 == -9999999, NaN, income_parent1)) %>%
  mutate(income_parent2 = ifelse(income_parent2 == -9999999, NaN, income_parent2))


# Negative travel time
df3 <- mutate(df3, travel_time = ifelse(travel_time < 0, NaN, travel_time))                    


# Omit missing variables 
df_sample <- df3 |>
  na.omit()


# Summarize the data again
skimr:: skim(df_sample)

# create new variables
df_sample <- df_sample |>
  mutate(income_parents = income_parent1 + income_parent2,
         travel_sq = travel_time^2)
```

# Question 1a)
```{r}

```

# Question 1b)
```{r}

```

# Question 2i)
```{r}

```

# Question 2ii)
```{r}

```

# Question 2iii)
```{r}

```

# Question 2iv)
```{r}

```